### ISSUE TITLE
post_permalink deprecated since WordPress 4.4

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/edd-social-discounts#8]
Seeing a debug notice in WP 4.4 due to `post_permalink()` being deprecated.

![image](https://cloud.githubusercontent.com/assets/1254870/11815360/4bd1a558-a319-11e5-8568-b5d7cb576a71.png)

Looks like it's used in two places.

**Comment by mintplugins** [comment]
A new customer request for fixing this here:
https://secure.helpscout.net/conversation/432050626/66770/?folderId=180499

P.S. I do not seem to have access to create branches on this repo.
